# Generated by Django 6.0 on 2026-01-06 01:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_promotion_productpromotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpromotion',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'Товар по акции', 'verbose_name_plural': 'Товары по акциям'},
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Автоматически заполняется при наличии акции', max_digits=10, null=True, verbose_name='Старая цена'),
        ),
        migrations.AddField(
            model_name='productpromotion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/banners/', verbose_name='Баннер'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='productpromotion',
            name='priority',
            field=models.IntegerField(default=1, help_text='От 1 до 10 (чем выше, тем выше приоритет)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='productpromotion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_promotions', to='store.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productpromotion',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_promotions', to='store.promotion', verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
